---
- name: Instalação do Cloudamize Agent em máquina Windows
  hosts: all
  gather_facts: no
  tasks:

    - name: Cria a pasta C:\temp se não existir
      win_file:
        path: C:\temp
        state: directory

    - name: Baixa o instalador do Cloudamize Agent
      win_get_url:
        url: https://downloads.arklok.com.br/cloudamizeAgent.msi
        dest: C:\temp\cloudamizeAgent.msi

    - name: Instala o Cloudamize Agent silenciosamente com chave do cliente
      win_package:
        path: C:\temp\cloudamizeAgent.msi
        arguments: 'customerkey=36ac2c88dcd15731685cbf254001fc04dd4584bdc6fbd2501e864f7d525632ef /qn'
        state: present
