---
- name: Instalação do Cloudamize Agent em servidores Linux
  hosts: all
  become: yes
  tasks:

    - name: Exporta variável de ambiente CLOUDAMIZE_CUSTOMER_KEY
      ansible.builtin.shell: |
        echo 'export CLOUDAMIZE_CUSTOMER_KEY=36ac2c88dcd15731685cbf254001fc04dd4584bdc6fbd2501e864f7d525632ef' >> /etc/profile.d/cloudamize.sh
        source /etc/profile.d/cloudamize.sh
      args:
        executable: /bin/bash

    - name: Executa script de instalação do Cloudamize Agent via curl e shell
      ansible.builtin.shell: |
        sh <(curl -L 'https://am.cloudamize.com/cxf/downloadFileV3?custkey=36ac2c88dcd15731685cbf254001fc04dd4584bdc6fbd2501e864f7d525632ef&filename=installCloudamizeAgentV2.sh')
      args:
        executable: /bin/bash

    - name: Faz o download do arquivo .hash (opcional para verificação)
      ansible.builtin.get_url:
        url: "https://am.cloudamize.com/cxf/downloadFileV3?custkey=36ac2c88dcd15731685cbf254001fc04dd4584bdc6fbd2501e864f7d525632ef&filename=installCloudamizeAgentV2.sh.hash"
        dest: /tmp/installCloudamizeAgentV2.sh.hash
