---
- name: Instalação do Cloudamize Agent em servidores Linux
  hosts: all
  become: yes
  tasks:

    - name: Baixa o script de instalação do Cloudamize Agent
      ansible.builtin.get_url:
        url: "https://am.cloudamize.com/cxf/downloadFileV3?custkey=36ac2c88dcd15731685cbf254001fc04dd4584bdc6fbd2501e864f7d525632ef&filename=installCloudamizeAgentV2.sh"
        dest: /tmp/installCloudamizeAgentV2.sh
        mode: '0755'

    - name: Executa o script de instalação com a variável customer key
      ansible.builtin.shell: |
        CLOUDAMIZE_CUSTOMER_KEY=36ac2c88dcd15731685cbf254001fc04dd4584bdc6fbd2501e864f7d525632ef \
        sh /tmp/installCloudamizeAgentV2.sh
      args:
        executable: /bin/bash

    - name: (Opcional) Baixa o arquivo de hash para verificação
      ansible.builtin.get_url:
        url: "https://am.cloudamize.com/cxf/downloadFileV3?custkey=36ac2c88dcd15731685cbf254001fc04dd4584bdc6fbd2501e864f7d525632ef&filename=installCloudamizeAgentV2.sh.hash"
        dest: /tmp/installCloudamizeAgentV2.sh.hash
      ignore_errors: yes
