---
- name: Adicionar entradas DNS no arquivo /etc/hosts
  hosts: all
  become: yes
  tasks:
    - name: Adiciona entradas no /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          # Entradas adicionadas via Ansible para ambientes Protheus
          192.168.200.24 mssqlprotheus.arkserv.local
          192.168.200.47 mssqlintegracao.arkserv.local
          192.168.150.24 mssqlprotheus-qas.arkserv.local
          192.168.150.24 mssqlintegracao-qas.arkserv.local
          192.168.120.24 mssqlprotheus-dev.arkserv.local
        marker: "# {mark} ANSIBLE-PROTHEUS"
