---
- name: Instala e registra o Zabbix Agent no Ubuntu
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    zabbix_server_ip: "192.168.200.37"
    zabbix_api_url: "http://192.168.200.37/zabbix"
    zabbix_api_user: "Admin"
    zabbix_api_pass: "33Uy`Njjr/Mnn$.$/C1N"
    zabbix_host_group: "SERVIDORES ARKLOK"
    zabbix_template_name: "Linux by Zabbix agent"

  tasks:

    - name: Determinar URL do pacote zabbix-release conforme versão
      set_fact:
        zabbix_release_url: >-
          {% set v = ansible_facts['distribution_version'] %}
          {% if v == '24.04' %}
            https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu24.04_all.deb
          {% elif v == '22.04' %}
            https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb
          {% elif v == '20.04' %}
            https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu20.04_all.deb
          {% elif v == '18.04' %}
            https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu18.04_all.deb
          {% else %}
            ''
          {% endif %}

    - name: Abortar se versão não suportada
      fail:
        msg: "Ubuntu {{ ansible_facts['distribution_version'] }} não é suportado."
      when: zabbix_release_url == ''

    - name: Baixar pacote zabbix-release
      get_url:
        url: "{{ zabbix_release_url }}"
        dest: /tmp/zabbix-release.deb
        mode: '0644'

    - name: Instalar pacote zabbix-release
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Atualizar cache APT
      apt:
        update_cache: yes

    - name: Instalar zabbix-agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configurar Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        state: present

    - name: Configurar ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"
        state: present

    - name: Configurar Hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        state: present

    - name: Iniciar e habilitar zabbix-agent
      systemd:
        name: zabbix-agent
        enabled: yes
        state: restarted

    - name: Gerar nome do host Zabbix baseado no IP
      set_fact:
        zabbix_hostname: >-
          {% set ip = ansible_facts['default_ipv4']['address'] %}
          {% set hn = ansible_facts['hostname'] | upper %}
          {% if ip.startswith('192.168') %}
            EQUINIX SP3 - {{ hn }}
          {% elif ip.startswith('10.10.4') %}
            ALPHAVILLE - {{ hn }}
          {% elif ip.startswith('10.10.0') or ip.startswith('172.18') %}
            ITAPEVI - {{ hn }}
          {% else %}
            DESCONHECIDO - {{ hn }}
          {% endif %}

    - name: Autenticar no Zabbix API (obter token)
      uri:
        url: "{{ zabbix_api_url }}/api_jsonrpc.php"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            user: "{{ zabbix_api_user }}"
            password: "{{ zabbix_api_pass }}"
          id: 1
          auth: null
      register: zabbix_auth_response

    - name: Registrar host via Zabbix API
      community.zabbix.zabbix_host:
        host_name: "{{ zabbix_hostname }}"
        visible_name: "{{ zabbix_hostname }}"
        host_groups:
          - "{{ zabbix_host_group }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_facts['default_ipv4']['address'] }}"
            dns: ""
            port: "10050"
        link_templates:
          - "{{ zabbix_template_name }}"
        status: enabled
        state: present
        server_url: "{{ zabbix_api_url }}"
        auth: "{{ zabbix_auth_response.json.result }}"
