---
- name: Instalar e configurar o Zabbix Agent com repositório oficial
  hosts: all
  become: yes
  vars:
    zabbix_version: "6.0"
    zabbix_server_ip: "192.168.200.37"

  tasks:

    - name: Detectar informações do sistema
      ansible.builtin.setup:
        gather_subset: min
      register: system_info

    - name: Adicionar repositório Zabbix no Debian/Ubuntu
      apt:
        deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_facts['os_family'] | lower }}/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+{{ ansible_facts['distribution_release'] | lower }}_all.deb"
      when: ansible_facts['os_family'] == "Debian"

    - name: Atualizar cache APT
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Adicionar repositório Zabbix no RHEL/CentOS
      get_url:
        url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_facts['distribution_major_version'] }}/x86_64/zabbix-release-{{ zabbix_version }}-1.el{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
        dest: /tmp/zabbix-release.rpm
      when: ansible_facts['os_family'] == "RedHat"

    - name: Instalar repositório RPM
      yum:
        name: /tmp/zabbix-release.rpm
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Atualizar cache YUM
      yum:
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Instalar o Zabbix Agent
      package:
        name: zabbix-agent
        state: present

    - name: Configurar o Server do Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        state: present
        backup: yes

    - name: Configurar o ServerActive do Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"
        state: present

    - name: Configurar o Hostname automático
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        state: present

    - name: Habilitar e iniciar o serviço do Zabbix Agent
      systemd:
        name: zabbix-agent
        enabled: yes
        state: restarted
