- name: Install all available Windows Updates
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install all updates
      ansible.windows.win_updates:
        state: installed
        category_names: '*'
        reboot: true
      timeout: 1500
      register: update_results

    - name: Show the updates results
      debug:
        var: update_results.updates
