---
- name: Instalar e configurar Zabbix Agent no Ubuntu (18.04, 20.04, 22.04, 24.04)
  hosts: all
  become: yes
  vars:
    zabbix_server_ip: "192.168.200.37"

  tasks:

    - name: Verificar versão do Ubuntu
      set_fact:
        ubuntu_version: "{{ ansible_facts['distribution_version'] }}"

    - name: Definir URL do pacote Zabbix release conforme a versão
      set_fact:
        zabbix_repo_url: >-
          {{ 'https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu' +
          (ubuntu_version | regex_replace('\\.', '')) + '_all.deb' }}

    - name: Baixar pacote do repositório Zabbix
      get_url:
        url: "{{ zabbix_repo_url }}"
        dest: "/tmp/zabbix-release.deb"

    - name: Instalar pacote .deb do repositório Zabbix
      apt:
        deb: "/tmp/zabbix-release.deb"
        state: present

    - name: Atualizar cache do APT
      apt:
        update_cache: yes

    - name: Instalar zabbix-agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configurar Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        state: present
        backup: yes

    - name: Configurar ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"
        state: present

    - name: Configurar Hostname automático
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        state: present

    - name: Iniciar e habilitar zabbix-agent
      systemd:
        name: zabbix-agent
        enabled: yes
        state: restarted
