- name: Teste de sudo no playbook
  hosts: local
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Executar whoami com sudo
      become: yes
      command: whoami
      register: resultado_sudo

    - name: Exibir resultado do sudo
      debug:
        var: resultado_sudo
