---
- name: Instala e registra o Zabbix Agent no Zabbix Server
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    zabbix_server_ip: "192.168.200.37"
    zabbix_api_url: "http://192.168.200.37/zabbix"
    zabbix_api_user: "Admin"
    zabbix_api_pass: "zabbix"  # ← Altere aqui sua senha real
    zabbix_host_group: "SERVIDORES ARKLOK"
    zabbix_template_name: "Linux by Zabbix agent"

  tasks:

    - name: Corrigir versão para 24.04 (usará pacote 22.04)
      set_fact:
        ubuntu_version_number: >-
          {% if ansible_facts['distribution_version'] == '24.04' %}
            2204
          {% else %}
            {{ ansible_facts['distribution_version'] | regex_replace('\\.', '') }}
          {% endif %}

    - name: Construir URL do pacote zabbix-release
      set_fact:
        zabbix_repo_url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu{{ ubuntu_version_number }}_all.deb"

    - name: Baixar pacote zabbix-release
      get_url:
        url: "{{ zabbix_repo_url }}"
        dest: "/tmp/zabbix-release.deb"

    - name: Instalar pacote zabbix-release
      apt:
        deb: "/tmp/zabbix-release.deb"
        state: present

    - name: Atualizar cache do APT
      apt:
        update_cache: yes

    - name: Instalar zabbix-agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configurar Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        state: present
        backup: yes

    - name: Configurar ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"
        state: present

    - name: Configurar Hostname automático
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        state: present

    - name: Habilitar e iniciar zabbix-agent
      systemd:
        name: zabbix-agent
        enabled: yes
        state: restarted

    - name: Definir nome do host conforme IP
      set_fact:
        zabbix_hostname: >-
          {% set ip = ansible_facts['default_ipv4']['address'] %}
          {% set hn = ansible_facts['hostname'] | upper %}
          {% if ip.startswith('192.168') %}
            EQUINIX SP3 - {{ hn }}
          {% elif ip.startswith('10.10.4') %}
            ALPHAVILLE - {{ hn }}
          {% elif ip.startswith('10.10.0') or ip.startswith('172.18') %}
            ITAPEVI - {{ hn }}
          {% else %}
            DESCONHECIDO - {{ hn }}
          {% endif %}

    - name: Adicionar host no Zabbix via API
      community.zabbix.zabbix_host:
        server_url: "{{ zabbix_api_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_pass }}"
        host_name: "{{ zabbix_hostname }}"
        visible_name: "{{ zabbix_hostname }}"
        groups:
          - "{{ zabbix_host_group }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_facts['default_ipv4']['address'] }}"
            dns: ""
            port: "10050"
        templates:
          - "{{ zabbix_template_name }}"
        status: 0
        state: present
