---
- name: Executar atualização via tarefa agendada distribuída por GPO
  hosts: all
  gather_facts: no
  vars:
    task_name: "AtualizarComPS7"

  tasks:

    - name: Forçar aplicação da GPO com gpupdate /force
      win_shell: gpupdate /force

    - name: Esperar 10 segundos para GPO aplicar tarefas agendadas
      pause:
        seconds: 10

    - name: Iniciar a tarefa agendada de atualização
      win_shell: |
        Start-ScheduledTask -TaskName "{{ task_name }}"

    - name: Aguardar a conclusão da tarefa agendada (versão simplificada)
      win_shell: 'do { Start-Sleep -Seconds 30; $s = (Get-ScheduledTaskInfo -TaskName "AtualizarComPS7").State } while ($s -ne "Ready")'
      args:
        executable: powershell.exe

    - name: (Opcional) Reiniciar o host após atualização
      win_reboot:
        reboot_timeout: 3600

    - name: Mensagem final
      debug:
        msg: "Atualização executada com sucesso via tarefa agendada."
