---
- name: Executar tarefa agendada "AtualizarComPS7" com PowerShell 7 e reiniciar
  hosts: all
  gather_facts: no
  vars:
    task_name: "AtualizarComPS7"

  tasks:

    - name: Forçar aplicação da GPO
      win_shell: gpupdate /force

    - name: Aguardar alguns segundos para a tarefa ser criada pela GPO
      pause:
        seconds: 10

    - name: Iniciar a tarefa agendada
      win_shell: |
        Start-ScheduledTask -TaskName "{{ task_name }}"
      args:
        executable: powershell.exe

    - name: Aguardar a conclusão da tarefa "{{ task_name }}"
      win_shell: '
        $maxWait = 60
        $counter = 0
        do {
          try {
            $taskInfo = Get-ScheduledTaskInfo -TaskName "{{ task_name }}" -ErrorAction Stop
            $status = $taskInfo.State
            Write-Host "Status da tarefa: $status"
            if ($status -eq "Ready") {
              break
            }
          } catch {
            Write-Host "Tarefa ainda não disponível. Aguardando..."
          }
          Start-Sleep -Seconds 30
          $counter++
        } while ($counter -lt $maxWait)
      '
      args:
        executable: powershell.exe

    - name: Reiniciar o host após a conclusão da tarefa
      win_reboot:
        reboot_timeout: 3600
        msg: "Atualizações aplicadas via tarefa agendada. Reiniciando sistema."

    - name: Mensagem final
      debug:
        msg: "Tarefa '{{ task_name }}' executada com sucesso e sistema reiniciado."
