---
- name: Atualizar Windows com PowerShell diretamente
  hosts: all
  gather_facts: no
  tasks:

    - name: Iniciar o serviço do Windows Update
      win_service:
        name: wuauserv
        start_mode: auto
        state: started

    - name: Forçar busca e instalação de atualizações
      win_shell: |
        Install-WindowsUpdate -MicrosoftUpdate -AcceptAll -AutoReboot -IgnoreReboot
      args:
        executable: powershell.exe
      register: resultado_atualizacao

    - name: Mostrar saída do comando PowerShell
      debug:
        var: resultado_atualizacao.stdout_lines
