- name: Install all available Windows Updates
  hosts: all
  gather_facts: no
  tasks:
    - name: Install all updates
      ansible.windows.win_updates:
        state: installed
        category_names: '*'
        reboot: true
      register: update_results
      ansible_winrm_connection_timeout: 1200 
      ansible_winrm_kerberos_delegation: true

    - name: Show the updates results
      debug:
        var: update_results.updates
