---
- name: Instalar PowerShell 7 (portátil) e aplicar atualizações no Windows
  hosts: all
  gather_facts: no
  tasks:

    - name: Garantir que o serviço do Windows Update está ativo
      win_service:
        name: wuauserv
        start_mode: auto
        state: started

    - name: Criar diretório de destino para o PowerShell 7
      win_file:
        path: 'C:\PowerShell7'
        state: directory

    - name: Baixar PowerShell 7.4.1 ZIP portátil
      win_get_url:
        url: "https://github.com/PowerShell/PowerShell/releases/download/v7.4.1/PowerShell-7.4.1-win-x64.zip"
        dest: "C:\\Temp\\PowerShell7.zip"

    - name: Descompactar PowerShell 7 em C:\PowerShell7
      win_unzip:
        src: "C:\\Temp\\PowerShell7.zip"
        dest: "C:\\PowerShell7"
        creates: "C:\\PowerShell7\\pwsh.exe"

    - name: Instalar PSWindowsUpdate no PowerShell 7
      win_shell: |
        C:\PowerShell7\pwsh.exe -Command "
          Install-PackageProvider -Name NuGet -Force;
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted;
          Install-Module -Name PSWindowsUpdate -Force
        "

    - name: Executar atualizações do Windows com PowerShell 7
      win_shell: |
        C:\PowerShell7\pwsh.exe -Command "
          Import-Module PSWindowsUpdate;
          Install-WindowsUpdate -MicrosoftUpdate -AcceptAll -AutoReboot
        "

    - name: Mensagem final
      debug:
        msg: "Atualizações aplicadas com PowerShell 7 portátil. O host pode reiniciar automaticamente."
