---
- name: Instala e registra o Zabbix Agent no Ubuntu
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    zabbix_server_ip: "192.168.200.37"
    zabbix_api_url: "http://192.168.200.37/zabbix"
    zabbix_api_user: "Admin"
    zabbix_api_pass: "33Uy`Njjr/Mnn$.$/C1N"  # Troque pela senha real
    zabbix_host_group: "SERVIDORES ARKLOK"
    zabbix_template_name: "Linux by Zabbix agent"

  tasks:

    - name: Definir pacote correto do zabbix-release por versão do Ubuntu
      set_fact:
        zabbix_release_url: >-
          {% set v = ansible_facts['distribution_version'] %}
          {% if v == '24.04' %}
            https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu24.04_all.deb
          {% elif v == '22.04' %}
            https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb
          {% elif v == '20.04' %}
            https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu20.04_all.deb
          {% elif v == '18.04' %}
            https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu18.04_all.deb
          {% else %}
            ''
          {% endif %}

    - name: Verificar se a versão é suportada
      fail:
        msg: "Ubuntu {{ ansible_facts['distribution_version'] }} não é suportado por este playbook."
      when: zabbix_release_url == ''

    - name: Baixar o pacote do repositório Zabbix
      get_url:
        url: "{{ zabbix_release_url }}"
        dest: "/tmp/zabbix-release.deb"
        mode: '0644'

    - name: Instalar o pacote do repositório Zabbix
      apt:
        deb: "/tmp/zabbix-release.deb"
        state: present

    - name: Atualizar cache APT
      apt:
        update_cache: yes

    - name: Instalar o Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configurar o Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        state: present
        backup: yes

    - name: Configurar o ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"
        state: present

    - name: Configurar o Hostname automático
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        state: present

    - name: Habilitar e iniciar o Zabbix Agent
      systemd:
        name: zabbix-agent
        enabled: yes
        state: restarted

    - name: Definir nome do host conforme IP
      set_fact:
        zabbix_hostname: >-
          {% set ip = ansible_facts['default_ipv4']['address'] %}
          {% set hn = ansible_facts['hostname'] | upper %}
          {% if ip.startswith('192.168') %}
            EQUINIX SP3 - {{ hn }}
          {% elif ip.startswith('10.10.4') %}
            ALPHAVILLE - {{ hn }}
          {% elif ip.startswith('10.10.0') or ip.startswith('172.18') %}
            ITAPEVI - {{ hn }}
          {% else %}
            DESCONHECIDO - {{ hn }}
          {% endif %}

    - name: Adicionar host no Zabbix via API
      community.zabbix.zabbix_host:
        server_url: "{{ zabbix_api_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_pass }}"
        host_name: "{{ zabbix_hostname }}"
        visible_name: "{{ zabbix_hostname }}"
        groups:
          - "{{ zabbix_host_group }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_facts['default_ipv4']['address'] }}"
            dns: ""
            port: "10050"
        templates:
          - "{{ zabbix_template_name }}"
        status: enabled
        state: present
