- name: Testar become com Ansible
  hosts: all
  gather_facts: no
  become: yes
  become_method: su

  tasks:
    - name: Mostrar usuario atual
      command: whoami
      register: resultado

    - name: Exibir resultado do whoami
      debug:
        var: resultado.stdout

    - name: Criar diretorio de teste em /opt
      file:
        path: /opt/teste_ansible
        state: directory
        mode: '0755'

    - name: Criar um arquivo de teste
      copy:
        dest: /opt/teste_ansible/ok.txt
        content: "Teste realizado com sucesso via Ansible become"
        owner: root
        group: root
        mode: '0644'
