---
- name: Listar TODAS as atualizações pendentes no Windows (inclusive Defender)
  hosts: all
  gather_facts: no
  tasks:

    - name: Buscar atualizações pendentes (todas as categorias)
      win_updates:
        state: searched
        log_path: C:\Temp\ansible-updates-log.txt
      register: updates_disponiveis

    - name: Exibir todas as variáveis retornadas para debug
      debug:
        var: updates_disponiveis

    - name: Exibir lista formatada de atualizações pendentes
      debug:
        msg: |
          {% if updates_disponiveis.updates is defined and updates_disponiveis.updates|length > 0 %}
          Atualizações encontradas:
          {% for update in updates_disponiveis.updates %}
          - {{ update.title }}
          {% endfor %}
          {% else %}
          Nenhuma atualização pendente encontrada.
          {% endif %}
