- name: Listar atualizações pendentes no Windows
  hosts: all
  gather_facts: no
  tasks:

      - name: Verificar atualizações pendentes
        win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - UpdateRollups
            - Updates
          state: searched  # Somente busca, não instala
      register: updates_disponiveis

    - name: Exibir lista de atualizações pendentes
      debug:
        msg: |
          Atualizações encontradas:
          {% for update in updates_disponiveis.updates %}
          - {{ update.title }}
          {% endfor %}
